
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    password: 123456
    username: root
rocketmq:
  name-server: 192.168.100.25:9876
  producer:
    group: producer-demo1
  consumer:
    group: consumer-demo1
mypro:
  a: 123
  b: 456
server:
  port: 8888